improved assertTrue and assertFalse to show appropriate error message: before, it showed null as error messages (which is easily mistakable for an NPE. Now, it shows expected <true> but was <false> and accordingly for assertFalse